name: macos_doc
description: "A Test Flutter project => MacOs Doc"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Riverpod
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

#  flutter_draggable_gridview: ^0.0.13
#
#  reorderable_plus: ^0.0.2
  flutter_reorderable_grid_view: ^5.4.1
#  flutter_sortable_wrap: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Riverpod
  build_runner:
  custom_lint:
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true

  assets:
    - assets/
